FROM resin/%%RESIN_MACHINE_NAME%%-debian

#switch on systemd init system in container
ENV INITSYSTEM on

RUN chmod +x configure.sh
RUN ./configure.sh

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN make debug
CMD make analyze
